<template>
  <div class="icl-item">
    <div class="icl-item-info">
      <div class="icl-item-info-title">Introduction</div>
      <p>
        ICL is ICLighthouse's eco-governance token, as well as a utility token
        consumed by the project. The token is used to incentivise users who
        contribute to the project's ecosystem.
      </p>
      <!--<p class="icl-item-info-margin">
        ICLighthouse is a Defi infrastructure based on the IC network, including
        ICLight (wallet), ICTokens (token issuance platform), CyclesFinance
        (Cycles marketplace), ICDex (spot Dex), ICStable (stablecoin),
        ICPStaking (ICP staking tool), ICMonitor (canister monitor),
        ICL-Accelerator (Defi eco-accelerator). These combinable functional
        modules can drive the development of the Defi eco-system of the IC
        network. ICLighthouse aims to develop into a distributed and autonomous
        community of developers and users (DAO), self-organising, self-managing
        and self-running according to a consensus mechanism set by a governance
        contract.
      </p>
      <p>
        Projects developed by the ICLighthouse team above will use ICL tokens
        for governance, incentive and utility use of the ecosystem. If projects
        developed by ICLighthouse issue tokens independently in response to
        market demand, at least 25% of the tokens will be airdropped to ICL
        holders. Projects incubated by ICL-Accelerator will be issued separate
        tokens at the discretion of their founders, as well as airdrops to ICL
        holders at their discretion.
      </p>-->
    </div>
    <div class="icl-item-info">
      <div class="icl-item-info-title">ICL Token</div>
      <p>Symbol: <span>ICL</span></p>
      <p>CanisterId: <span>5573k-xaaaa-aaaak-aacnq-cai</span></p>
      <p>Decimals: <span>8</span></p>
      <p>TotalSupply: <span>Approx. 210,000,000</span></p>
      <p>Rules of distribution (based on a total of 210,000,000):</p>
      <ul>
        <li>
          <span class="round"></span>51% ICL is distributed to the community,
          through airdrops, mining, community rewards, etc.
        </li>
        <li><span class="round"></span>29% ICL is distributed to investors.</li>
        <li>
          <span class="round"></span>15% ICL is distributed to project
          developers and operational contributors.
        </li>
        <li><span class="round"></span>5% ICL reserved.</li>
      </ul>
    </div>
    <div class="icl-item-info">
      <div class="icl-item-info-title">ICL economic model</div>
      <p>ICL is used as a deflationary economic model.</p>
      <div class="icl-item-info-title mt20">Use of tokens</div>
      <ul>
        <li>
          <span class="round"></span>Paid as a fee in the project and destroyed.
        </li>
        <li>
          <span class="round"></span>A portion of the proceeds generated by the
          project is used to repurchase ICL for destruction.
        </li>
        <li>
          <span class="round"></span>As a qualification, priority to use a
          functionality in the project.
        </li>
        <li>
          <span class="round"></span>As a governance voting qualification.
        </li>
      </ul>
      <div class="icl-item-info-title mt20">Gains to holders</div>
      <p>
        ICLs are held for governance and utility purposes. No person or entity
        has committed value to ICLs and you can treat ICLs as worthless. If you
        hold ICLs, you do so at your own risk.
      </p>
    </div>
    <div class="icl-item-info mt20">
      <div class="icl-item-info-title">Disclaimer</div>
      <p>
        ICLighthouse is a dapp, the wallet is non-custodial and you use it with
        knowledge and at your own risk, no person or entity guarantees your
        assets.This application is not legally allowed in certain regions and
        users are requested to comply with local laws and regulations and bear
        all legal risks.
      </p>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component({
  name: 'About',
  components: {}
})
export default class extends Vue {}
</script>

<style scoped lang="scss">
.icl-item-info {
  background: #141b23;
  border-radius: 10px;
  padding: 20px 30px;
  color: #8c98a5;
  line-height: 1.5;
  p > span {
    font-weight: bold;
    color: #adb7c2;
  }
  .icl-item-info-margin {
    margin: 10px 0;
  }
  .icl-item-info-title {
    color: #adb3c4;
    font-size: 18px;
    margin-bottom: 10px;
  }
}
li {
  display: flex;
  align-items: center;
}
.round {
  display: inline-block;
  width: 6px;
  height: 6px;
  margin-right: 10px;
  border-radius: 3px;
  background: #666;
}
.text-indent {
  padding-left: 1em;
}
</style>
